fix: avoid after feature error and add dynamic environment tests
Telefonica/toolium pull request #348
Opened 2023-05-15 15:13 UTC by rgonalo

2023-05-17 09:30 UTC, iariasleon submitted a review, later dismissed
LGTM

2023-05-17 12:45 UTC, AlainMiranda submitted a review, later dismissed

2023-05-18 14:43 UTC, pabloge requested changes

2023-05-18 14:43 UTC, pabloge commented on toolium/test/behave/test_env_utils.py
> +    context.execute_steps.side_effect = Exception('Exception in before scenario step')
```suggestion
    context.execute_steps.side_effect = Exception('Exception in after scenario step')
```

2023-05-18 15:16 UTC, pabloge approved these changes

2023-05-19 07:04 UTC, merged