Allow list search in CONTEXT
Telefonica/toolium pull request #353
Opened 2023-06-08 10:38 UTC by lmcalvo

2023-06-15 13:39 UTC, pabloge requested changes

2023-06-15 13:39 UTC, pabloge commented on CHANGELOG.rst
> +- Update `[CONTEXT:a.b.c]` to allow list access in context, f.e: context.list.1 access to the second element of list
```suggestion
- Update `[CONTEXT:a.b.c]` replacement to allow lists access, e.g. [CONTEXT:list.1] to access the second element of list
```

2023-06-15 13:39 UTC, pabloge commented on toolium/test/utils/test_dataset_map_param_context.py
> +    Verification of a list without index as CONTEXT to get all the list, not a element in the list
```suggestion
    Verification of a list without index as CONTEXT to get all the list, not an element in the list
```

2023-06-15 13:39 UTC, pabloge commented on toolium/test/utils/test_dataset_map_param_context.py
> +    Verification of a list with a no numeric index as CONTEXT
```suggestion
    Verification of a list with a non-numeric index as CONTEXT
```

2023-06-15 13:39 UTC, pabloge commented on toolium/test/utils/test_dataset_map_param_context.py
> +    Verification of a class with a no numeric index as CONTEXT
```suggestion
    Verification of a class with a non-numeric index as CONTEXT
```

2023-06-15 13:39 UTC, pabloge commented on toolium/utils/dataset.py
> +    f.e: list.1 returns the second element of the list 'list'.
```suggestion
    If the resolved element at one of the tokens is a list, then the next token (if present) is used as the index
    to select one of its elements, e.g. "list.1" returns the second element of the list "list".
```

2023-06-15 13:39 UTC, pabloge commented on toolium/utils/dataset.py
> +        if msg:
This `if` is no longer needed: `msg` is always set in the previous line (and only there).
```suggestion
```

2023-06-15 13:39 UTC, pabloge commented on toolium/utils/dataset.py
> +    :return: errors
```suggestion
    Returns an appropriate error message when an error occurs resolving a CONTEXT reference.

    :param value: last value that has been correctly resolved
    :param part: token that is causing the error
    :return: a string with the error message
```

2023-06-15 13:39 UTC, pabloge commented on toolium/utils/dataset.py
> +            msg = get_value_context_errors(value, part)
I would rather make it private, it does not seem to be very reusable outside this module.
```suggestion
            msg = _get_value_context_error_msg(value, part)
```

2023-06-15 13:39 UTC, pabloge commented on toolium/utils/dataset.py
> +def get_value_context_errors(value, part):
I would rather make it private, it does not seem very reusable outside this module.
```suggestion
def _get_value_context_error_msg(value, part):
```

2023-06-16 07:29 UTC, pabloge approved these changes
LGTM

2023-06-16 07:40 UTC, rgonalo approved these changes

2023-06-16 12:31 UTC, merged