bug(QAWTO-212): fix action before the feature with background output
Telefonica/toolium pull request #397
Opened 2024-06-28 11:45 UTC by ricardogarfe

fix: dynamic environment error output for a feature with:
* action before the feature error
* with background

h2. Current output

Current output scenarios without failure because `background` is not updated with fail status:
```shell
0 features passed, 1 failed, 0 skipped
0 scenarios passed, 0 failed, 0 skipped, 2 untested
0 steps passed, 2 failed, 0 skipped, 0 undefined, 2 untested
```

h2. Corrected output

console log:
```shell
0 features passed, 1 failed, 0 skipped
0 scenarios passed, 2 failed, 0 skipped
0 steps passed, 2 failed, 0 skipped, 0 undefined
```

To generate correct report xml output:
```xml
<testsuite name="1_fail.Fail feature with a single scenario" tests="2" errors="2"
  failures="0" skipped="0" time="0.0" timestamp="2024-06-28T13:14:40.358338"
  hostname="mac-GR4Y6N937D">
  <testcase classname="1_fail.Fail feature with a single scenario"
    name="First scenario won't be executed due to failed before feature" status="failed" time="0">
    <error type="Exception" message="Preconditions failed">
<![CDATA[
Failing step: Given this step won't be executed ... failed in 0.000s
Location: features/integration/fail.feature:11
FAILED SUB-STEP: Given a failed step
Substep info: Assertion Failed: FAILED SUB-STEP: Given a failed sub-step exception
Substep info: Traceback (most recent call last):
    raise Exception("Sorry, no lucky day!")
]]>
</error>
    <system-out>
<![CDATA[
@scenario.begin

  @regression @sanity
  Scenario: First scenario won't be executed due to failed before feature
    Given this step won't be executed ... failed in 0.000s
    Given I hope this generates test report ... failed in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out>
  </testcase>
</testsuite>
```

2024-06-28 11:51 UTC, jordipuigbou approved these changes

2024-06-28 11:52 UTC, jordipuigbou commented on toolium/behave/env_utils.py
> +                        context.logger.warn(f'Background from scenario status udpated to fail')
```suggestion
                        context.logger.warn('Background from scenario status udpated to fail')
```

2024-06-28 11:53 UTC, jordipuigbou commented on toolium/behave/env_utils.py
> +                        context.logger.warn(f'Background from scenario status udpated to fail')
Falla el linter aquí @ricardogarfe

2024-06-28 11:57 UTC, rgonalo requested changes

2024-06-28 11:57 UTC, rgonalo commented on toolium/behave/env_utils.py
> +from behave.model_core import Status
An import error will be raised here when tests do not use behave

2024-06-28 14:31 UTC, ricardogarfe commented on toolium/behave/env_utils.py
> +        # Behave is an optional dependency in toolium, so it is imported here
Lo había puesto a nivel del módulo pero lo he dejado donde estaba por el comentario de @rgonalo https://github.com/Telefonica/toolium/pull/397#discussion_r1658636392

Ese cambio que comentas debería ir en otra pr por todo lo que pudiese afectar 👍🏽

2024-06-28 15:40 UTC, jframos approved these changes
LGTM

2024-07-01 08:21 UTC, rgonalo approved these changes

2024-07-04 06:55 UTC, merged