QAWTO-214: update appium python client dependency
Telefonica/toolium pull request #404
Opened 2024-10-29 15:34 UTC by hesteban-tuenti

As part of the maintenance of the toolium dependency libraries, the update of the appium python client is going to be update to the version 4.
In order to update to this version we identified that the following actions needed to be updated to be compatible with the w3C webdriver:
https://jira.tid.es/browse/QAWTO-178

In order to be fully W3C compatible we need to change the set_value method used in the InputText pagelement to send_keys

2024-10-29 15:39 UTC, hesteban-tuenti commented
reviso los tests cuando tenga un momento

2024-10-29 16:09 UTC, rgonalo requested changes

2024-10-29 16:09 UTC, rgonalo commented on toolium/pageelements/input_text_page_element.py
> -            return self.web_element.get_attribute("label")
si funciona con .get_attribute("value") déjalo así, pero tienes que actualizar los tests unitarios para que no fallen

2024-10-29 16:09 UTC, rgonalo commented on requirements.txt
> +Appium-Python-Client==4.0.1 # mobile tests
no deberíamos tener una versión fija, sólo la mínima, debería ser por ejemplo
Appium-Python-Client~=4.0

2024-11-08 13:37 UTC, hesteban-tuenti commented
I have tested the new mobile_actions features (Android e iOS) which tests all of the detected changes in Appium 3 , and 4 and also the change in the InputText done in this PR with the following versions:

 * Appium-Python-Client= 2.11.1 - Selenium=4.11.2
 * Appium-Python-Client= 3.2.1 - Selenium=4.25
 * Appium-Python-Client= 4.2.1  Selenium=4.25

And the results have been OK

2024-11-08 15:10 UTC, hesteban-tuenti commented on README.rst
> +You might need to adjust the Selenium and Appium-Python-Client versions in your project.
WDYT?

2024-11-20 14:06 UTC, rgonalo submitted a review, later dismissed

2024-11-25 16:36 UTC, merged